spring:
  application:
    name: zxb-ai-agent
  ai:
    openai:
      api-key: ${OPENAI_APIKEY}
      base-url: ${OPENAI_BASEURL:https://api.openai.com}
      chat:
        model: qwen3.8:27b-fast
        temperature: 0.7
        max-tokens: 1000
      embedding:
        base-url: ${EMBEDDING_BASEURL:http://localhost:11434/v1}
        model: ${EMBEDDING_MODEL:nomic-embed-text:latest}
